spring.application.name=study-project-spring
# → 存在しないURLにアクセスした時に NoHandlerFoundException を投げる
spring.mvc.throw-exception-if-no-handler-found=true
# → Spring Boot のデフォルトのエラーページ（Whitelabel Error Page）を無効化
spring.web.resources.add-mappings=false

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
mybatis.type-aliases-package=study.model