spring.application.name=study-project-spring
# → 存在しないURLにアクセスした時に NoHandlerFoundException を投げる
spring.mvc.throw-exception-if-no-handler-found=true
# → Spring Boot のデフォルトのエラーページ（Whitelabel Error Page）を無効化
spring.web.resources.add-mappings=false
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database
spring.datasource.username=your_user
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver
