spring.application.name=study-project-spring
# → 存在しないURLにアクセスした時に NoHandlerFoundException を投げる
spring.mvc.throw-exception-if-no-handler-found=true
# → Spring Boot のデフォルトのエラーページ（Whitelabel Error Page）を無効化
spring.web.resources.add-mappings=false
spring.datasource.url=jdbc:postgresql://localhost:5432/studydb
spring.datasource.username=juth5
spring.datasource.password=onefukaga55
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.mapper-locations=classpath:mybatis/mapper/xml/*.xml

mybatis.type-aliases-package=study.model